<?php//sjsjssnsnsnsn
	$db=mysqli_connect("localhost","root","","ecom_store");
	function(){
		global $db;
	}//nnsnssnsnsnssnnssnsnsnsnssnlalalasnsnssnsnnssssnsnnssssnsnnsnnnsbncncn n n xcncnzsnsnsnsnssbzssnsnsnssnsnsnsnsnnsnnsznznnsnssnsnsnnxnxnsnsnsnncncnznzzbnxznznznssnssnznznzsssnsnxnxnsnnsssxnxnsnsnsnjssksksknxnxjsjssnsnsjsjsjssjsjjsnnsnssnsnsnsnxssnsnsnxsnsnsnbbxbssnsnsnsnsnsnsnssnss sbbnsnsnsnsnss s nsnnsnxssnsnsnssnssnssnsnsnnssnsnssn nnsnsnssnssnsnsnnsnsnsnsnssnsnssnsnxsnsnsnnsnsnsnxnxxnxnsnsnssnsnsnsnsnssnsnsnsnssnsnsnsnsnsnsnsskskksnsnssnsnsnsssnsnsnxssnsnsnsnsnnsnnsnxnsnsnsnnsnsnssnsnnx nsnsnsnsnzbbzbsnsnszsssnsnmsmnznznzxsnsnnsmsmxnnzzsnnznzxnxncncnxsnsnnznznnsnnsxnwwhhwsnsnsxbxbsnsns
?>