<?php//sjsjssnsnsnsn
	$db=mysqli_connect("localhost","root","","ecom_store");
	function(){
		global $db;
	}//nnbzbzbnxnssnsnsnsnsnsnxssnsnsnssnsnsnsnsnsnsnss s nsnnsnxssnsnsnssnssnssnsnsnnssnsnssn nnsnsnssnssnsnsnnsnsnsnsnssnsnssnsnxsnsnsnnsnsnsnxnxxnxnsnsnssnsnsnsnsnssnsnsnsnssnsnsnsnsnsnsnsskskksnsnssnsnsnsssnsnsnxssnsnsnsnsnnsnnsnxnsnsnsnnsnsnssnsnnx nsnsnsnsnzbbzbsnsnszsssnsnmsmnznznzxsnsnnsmsmxnnzzsnnznzxnxncncnxsnsnnznznnsnnsxnwwhhwsnsnsxbxbsnsns
?>