<?php//sjsjssnsnsnsn
	$db=mysqli_connect("localhost","root","","ecom_store");
	function(){
		global $db;
	}//nnbzbzsnsnnsznznsnsnnsnncncnznzzbnxznznznssnssnznznzsssnsnxnxnsnnsssxnxnsnsnsnjssksksknxnxjsjssnsnsjsjsjssjsjjsnnsnssnsnsnsnxssnsnsnxsnsnsnbbxbssnsnsnsnsnsnsnssnss sbbnsnsnsnsnss s nsnnsnxssnsnsnssnssnssnsnsnnssnsnssn nnsnsnssnssnsnsnnsnsnsnsnssnsnssnsnxsnsnsnnsnsnsnxnxxnxnsnsnssnsnsnsnsnssnsnsnsnssnsnsnsnsnsnsnsskskksnsnssnsnsnsssnsnsnxssnsnsnsnsnnsnnsnxnsnsnsnnsnsnssnsnnx nsnsnsnsnzbbzbsnsnszsssnsnmsmnznznzxsnsnnsmsmxnnzzsnnznzxnxncncnxsnsnnznznnsnnsxnwwhhwsnsnsxbxbsnsns
?>